//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace l10_test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Czlonkowie
    {
        public int Id { get; set; }
        public int IdKola { get; set; }
        public int Rola { get; set; }
        public bool Aktywny { get; set; }
        public int IdUzytkownika { get; set; }
    
        public virtual KoloNaukowe KoloNaukowe { get; set; }
        public virtual Uzytkownik Uzytkownik { get; set; }
    }
}
