//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace l10_test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KoloNaukowe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KoloNaukowe()
        {
            this.Portfolio = new HashSet<Portfolio>();
            this.Czlonkowie = new HashSet<Czlonkowie>();
            this.Post = new HashSet<Post>();
        }
    
        public int Id { get; set; }
        public string Nazwa { get; set; }
        public System.DateTime DataUtworzenia { get; set; }
        public int Uczelnia { get; set; }
        public bool Aktywny { get; set; }
        public System.DateTime DataDoUsuniecia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Portfolio> Portfolio { get; private set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Czlonkowie> Czlonkowie { get; private set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Post> Post { get; private set; }
    }
}
