//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace l10_test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Portfolio
    {
        public int Id { get; set; }
        public int IdKola { get; set; }
        public string Zawartosc { get; set; }
        public System.DateTime DataUtworzenia { get; set; }
    
        public virtual KoloNaukowe KoloNaukowe { get; set; }
    }
}
