//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace l10_test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wiadomosc
    {
        public int Id { get; set; }
        public int IdOdbiorcy { get; set; }
        public int IdNadawcy { get; set; }
        public string Zawartosc { get; set; }
        public string Tytul { get; set; }
        public System.DateTime DataPrzeslania { get; set; }
        public System.DateTime DataOdebrania { get; set; }
    
        public virtual Uzytkownik Nadawca { get; set; }
        public virtual Uzytkownik Odbiorca { get; set; }
    }
}
