//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektIO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Czlonkowie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Czlonkowie()
        {
            this.Komentarz = new HashSet<Komentarz>();
            this.Post = new HashSet<Post>();
        }
    
        public int Id { get; set; }
        public int IdKola { get; set; }
        public int Rola { get; set; }
        public bool Aktywny { get; set; }
        public int IdUzytkownika { get; set; }
    
        public virtual KoloNaukowe KoloNaukowe { get; set; }
        public virtual Uzytkownik Uzytkownik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Komentarz> Komentarz { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Post> Post { get; set; }
    }
}
