//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektIO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Komentarz
    {
        public int Id { get; set; }
        public int IdPostu { get; set; }
        public string Zawartosc { get; set; }
        public System.DateTime DataPrzeslania { get; set; }
        public int IdUzytkownika { get; set; }
    
        public virtual Post Post { get; set; }
    }
}
