//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektIO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Post()
        {
            this.Komentarz = new HashSet<Komentarz>();
        }
    
        public int Id { get; set; }
        public int IdUzytkownika { get; set; }
        public int IdKola { get; set; }
        public string Zawartosc { get; set; }
        public System.DateTime DataUtworzenia { get; set; }
        public bool Przypiety { get; set; }
    
        public virtual KoloNaukowe KoloNaukowe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Komentarz> Komentarz { get; set; }
    }
}
